// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXb0mpL9kja9h9m9CUwNtg-1lkNKNZjQk',
    appId: '1:548997051209:android:548ecb74d68814a1bb6098',
    messagingSenderId: '548997051209',
    projectId: 'boichokro-4d669',
    storageBucket: 'boichokro-4d669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT6eLzPLswetNMaGO7VfsRV3kKdA2yJDo',
    appId: '1:548997051209:ios:5c95c2792e097686bb6098',
    messagingSenderId: '548997051209',
    projectId: 'boichokro-4d669',
    storageBucket: 'boichokro-4d669.firebasestorage.app',
    androidClientId: '548997051209-ngl9vi4fiq9r648j4pemi58kman0bfoo.apps.googleusercontent.com',
    iosClientId: '548997051209-4264i7ad5p0gk5s2cqggmkdbcj58euep.apps.googleusercontent.com',
    iosBundleId: 'com.programmernexus.boichokro',
  );

}